channel_targets:
  - conda-forge main
c_compiler_version:            # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
cxx_compiler_version:          # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
fortran_compiler_version:      # [unix]
  - 12                         # [linux]
  - 12                         # [osx]
llvm_openmp:                              # [osx]
  - 16                                    # [osx]
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.11.* *_cpython
python_impl:
  - cpython
apr:
  - '1'
boost:
  - 1.78.0
cffi:
  - '1'
cfitsio:
  - 4.3.0
cython:
  - '0'
eigen:
  - '3.4'
gsl:
  - '2.7'
libaprutil:
  - '1'
libcxx:
  - '16'
log4cxx:
  - 1.1.0
minuit2:
  - '6'
ndarray:
  - '1'
numpy:
  - '1.24'
starlink_ast:
  - '9.2.10'
wcslib:
  - '7'
xpa:
  - '2'
yaml_cpp:
  - '0.7'
