channel_targets:
  - conda-forge main
c_compiler_version:            # [unix]
  - 10                         # [linux]
  - 14                         # [osx]
cxx_compiler_version:          # [unix]
  - 10                         # [linux]
  - 14                         # [osx]
fortran_compiler_version:      # [unix]
  - 10                         # [linux]
  - 11                         # [osx and x86_64]
  - 11                         # [osx and arm64]
llvm_openmp:                              # [osx]
  - 13                                    # [osx]
python:
  # part of a zip_keys: python, python_impl, numpy, is_python_min
  - 3.10.* *_cpython
is_python_min:
  - false
python_impl:
  - cpython
apr:
  - '1'
boost:
  - 1.78.0
cffi:
  - '1'
cfitsio:
  - 4.1.0
cython:
  - '0'
eigen:
  - '3.4'
gsl:
  - '2.7'
libaprutil:
  - '1'
log4cxx:
  - 0.11.0
minuit2:
  - '6'
mpich:
  - '3'
ndarray:
  - '1'
numpy:
  - '1.21'
starlink_ast:
  - '9.2.7'
wcslib:
  - '7.7'
xpa:
  - '2'
yaml_cpp:
  - '0.7'
