channel_targets:
  - conda-forge main
c_compiler_version:            # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
fortran_compiler_version:      # [unix]
  - 13                         # [linux]
  - 13                         # [osx]
rust_complier_version:
  - 1.89.0
llvm_openmp:                              # [osx]
  - 18                                    # [osx]
python:
  # part of a zip_keys: python, python_impl, numpy, is_python_min
  - 3.12.* *_cpython
is_python_min:
  - false
python_impl:
  - cpython
apr:
  - '1'
cffi:
  - '1'
cfitsio:
  - 4.6.2
cython:
  - '3'
eigen:
  - '3.4'
gsl:
  - '2.7'
libaprutil:
  - '1'
libboost_python_devel:
  - '1.86'
libcxx:
  - '18'
log4cxx:
  - 1.2.0
minuit2:
  - '6.34'
ndarray:
  - '1'
starlink_ast:
  - '9.2.14'
wcslib:
  - '8'
xpa:
  - '2'
yaml_cpp:
  - '0.8'

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
